// Code generated by "gorm-gen"; DO NOT EDIT.

package dao

import (
	"context"
	"github.com/Kotodian/gorm-gen/examples/models/special"
	"gorm.io/gorm"
)

// CreateErr create object
func CreateErr(ctx context.Context, db *gorm.DB, err *special.Err) error {
	return db.WithContext(ctx).Create(err).Error
}

// ListErr list objects
func ErrList(ctx context.Context, db *gorm.DB) ([]*special.Err, error) {
	errs := make([]*special.Err, 0)
	err := db.WithContext(ctx).Where("deleted_at=0").Find(&errs).Error
	return errs, err
}

// QueryErr query objects by condition
func ErrQuery(ctx context.Context, db *gorm.DB, args map[string]interface{}) ([]*special.Err, error) {
	errs := make([]*special.Err, 0)
	err := db.WithContext(ctx).Where(args).Where("deleted_at=0").Find(&errs).Error
	return errs, err
}

// UpdateErr update object
func UpdateErr(ctx context.Context, db *gorm.DB, args map[string]interface{}) error {
	return db.WithContext(ctx).Model(&special.Err{}).Updates(args).Error
}

// DeleteErr delete object
func DeleteErr(ctx context.Context, db *gorm.DB, err special.Err) error {
	return db.WithContext(ctx).Delete(&err).Error
}
